### ISSUE TITLE
Cutechess only provides 3 decimal places in the result

### ISSUE THREAD

**Issue by joergoster** [fsmosca/Optuna-Game-Parameter-Tuner#2]
I'm afraid simply fetching the result from cutechess deosn't provide the needed precision for the tuner.
See https://github.com/fsmosca/Optuna-Game-Parameter-Tuner/blob/master/tuner.py#L157-L160

Noticed this while running a session with 8,000 games per trial (fixed depth) and getting continuously similar results.

**Comment by fsmosca** [comment]
Thanks, I will increase it.

**Comment by joergoster** [comment]
Thank you!
